name: Auto version bump on merge to UAT

on:
  push:
    branches:
      - uat

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if changes come from dev branch
        id: check-dev-branch
        run: |
          last_commit_title=$(git log --format='%s' -1)
          if [[ "$last_commit_title" == *"Merge branch 'dev' * into uat"* ]]; then
            echo "IS_DEV=0" >> $GITHUB_ENV
          else
            echo "IS_DEV=1" >> $GITHUB_ENV
          fi

      - name: Checkout dev branch
        if: env.IS_DEV == '0'
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set git user identity
        if: env.IS_DEV == '0'
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Set up Node.js
        if: env.IS_DEV == '0'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Bump version
        if: env.IS_DEV == '0'
        run: npm version patch --force

      - name: Push changes to dev branch
        if: env.IS_DEV == '0'
        run: git push origin dev
