name: Auto version bump on merge to UAT

on:
  push:
    branches:
      - uat

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get last commit title
        id: get-last-commit-title
        run: |
          last_commit_title=$(git log --merges --first-parent --decorate --oneline -1)
          echo "Last commit title: $last_commit_title" 

      - name: Check if changes come from dev branch
        if: contains(steps.get-last-commit-title.outputs.last_commit_title, 'dev')
        run: |
          echo "Changes come from dev branch"
          echo "IS_DEV=0" >> $GITHUB_ENV

      - name: Check if changes come from other branches
        if: contains(steps.get-last-commit-title.outputs.last_commit_title, 'dev') == false
        run: |
          echo "Changes come from other branches"
          echo "IS_DEV=1" >> $GITHUB_ENV

      - name: Checkout dev branch
        if: env.IS_DEV == '0'
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set git user identity
        if: env.IS_DEV == '0'
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Set up Node.js
        if: env.IS_DEV == '0'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Bump version
        if: env.IS_DEV == '0'
        run: npm version patch --force

      - name: Push changes to dev branch
        if: env.IS_DEV == '0'
        run: git push origin dev
