name: Bump DEV patch version after merging to UAT

on:
  push:
    branches:
      - uat

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get last commit message
        id: get-last-commit-message
        run: |
          last_commit_message=$(git log -1 --pretty=format:%s)

          echo "last_commit_message=${last_commit_message}" >> $GITHUB_OUTPUT
          echo "dev_branch_name=${{ github.repository_owner }}/dev" >> $GITHUB_OUTPUT

      - name: Check if changes come from dev branch
        if: contains(steps.get-last-commit-message.outputs.last_commit_message, steps.get-last-commit-message.outputs.dev_branch_name)
        run: echo "IS_DEV=true" >> $GITHUB_ENV

      - name: Checkout dev branch
        if: env.IS_DEV == 'true'
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set git user identity
        if: env.IS_DEV == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up Node.js
        if: env.IS_DEV == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Bump version and push changes to dev branch
        if: env.IS_DEV == 'true'
        run: |
          git checkout dev-bump-version-patch
          npm version patch --force
          git push origin dev-bump-version-patch --force --no-verify
