name: Auto version bump on merge to UAT

on:
  push:
    branches:
      - uat

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if changes come from dev branch
        id: check-dev-branch
        run: |
          echo "Source branch: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            source_branch="${{ github.event.pull_request.head.ref }}"
          else
            source_branch="${{ github.ref }}"
          fi
          echo "Source branch: $source_branch"
          if [[ "$source_branch" == "refs/heads/dev" ]]; then
            is_dev=0
          else
            is_dev=1
          fi
          echo "IS_DEV=$is_dev" >> $GITHUB_ENV
          echo "IS_DEV is set to $is_dev"

      - name: Set up Node.js
        if: env.IS_DEV == '0'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        if: env.IS_DEV == '0'
        run: npm install

      - name: Bump version
        if: env.IS_DEV == '0'
        run: npm version patch --force

      - name: Push changes to dev branch
        if: env.IS_DEV == '0'
        run: git push origin dev
