name: Auto version bump on merge to UAT

on:
  push:
    branches:
      - uat

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check if changes come from dev branch
        id: check-dev-branch
        run: echo "::set-output name=is_dev::$(git log --merges --first-parent --format='%s' -1 | grep -q 'Merge branch '\''dev'\''; echo $?)"

      - name: Checkout dev branch
        if: steps.check-dev-branch.outputs.is_dev == '0'
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Set up Node.js
        if: steps.check-dev-branch.outputs.is_dev == '0'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Bump version
        if: steps.check-dev-branch.outputs.is_dev == '0'
        run: npm version patch --force

      - name: Push changes to dev branch
        if: steps.check-dev-branch.outputs.is_dev == '0'
        run: git push origin dev
