name: Auto version bump on merge to UAT

on:
  push:
    branches:
      - uat

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if changes come from dev branch
        id: check-dev-branch
        run: |
          git log --merges --first-parent --format='%s' -1
          is_dev=$(git log --merges --first-parent --format='%s' -1 | grep -qE "Merge branch ('|\")dev('|\")"; echo $?)
          echo "IS_DEV=$is_dev" >> $GITHUB_ENV
          echo "IS_DEV is set to $is_dev"

      - name: Set up Node.js
        if: env.IS_DEV == '0'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        if: env.IS_DEV == '0'
        run: npm install

      - name: Bump version
        if: env.IS_DEV == '0'
        run: npm version patch --force

      - name: Push changes to dev branch
        if: env.IS_DEV == '0'
        run: git push origin dev
