name: Auto version bump on merge to UAT

on:
  push:
    branches:
      - uat

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if changes come from dev branch
        id: check-dev-branch
        run: |
          if ${{ env.SOURCE_BRANCH }} == 'dev'; then
            is_dev=0
          else
            is_dev=1
          fi
          echo "source branch is ${{ env.SOURCE_BRANCH }}"
          echo "IS_DEV=$is_dev" >> $GITHUB_ENV
          echo "IS_DEV is set to $is_dev"

      - name: Checkout dev branch
        if: steps.check-dev-branch.outputs.is_dev == '0'
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set git user identity
        if: steps.check-dev-branch.outputs.is_dev == '0'
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Set up Node.js
        if: steps.check-dev-branch.outputs.is_dev == '0'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # - name: Install dependencies
      #   if: steps.check-dev-branch.outputs.is_dev == '0'
      #   run: npm install

      - name: Bump version
        if: steps.check-dev-branch.outputs.is_dev == '0'
        run: npm version patch --force

      - name: Push changes to dev branch
        if: steps.check-dev-branch.outputs.is_dev == '0'
        run: git push origin dev
