name: Merge PR from dev-bump-version-patch to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge pull request
        if: github.event.pull_request.head.ref == 'dev-bump-version-patch'
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: merge