name: Merge PR from dev-bump-version-patch to dev

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - dev

jobs:
  merge_dev_bump_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge pull request
        if: github.event.pull_request.head.ref == 'dev-bump-version-patch'
        uses: actions/github-script@v6
        with:
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repository = context.repo

            await github.rest.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: pullRequest.number,
              repo: repository.repo,
            })