# name: Merge PR from dev-bump-version-patch to dev

# on:
#   workflow_run:
#     workflows: ['Bump DEV patch version after merging to UAT']
#     types:
#       - completed

# jobs:
#   merge_dev_bump_pull_request:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set git user identity
#         if: env.IS_DEV == 'true'
#         run: |
#           git config user.name github-actions
#           git config user.email github-actions@github.com

#       - name: Merge pull request
#         if: github.context.payload.workflow_run.head_repository.default_branch == 'dev' && github.context.payload.workflow_run.head_branch == 'dev-bump-version-patch'
#         uses: actions/github-script@v7
#         with:
#         env:
#           GITHUB_TOKEN: ${{ secrets.PUSH_TO_DEV }}
#           script: |
#             await github.rest.pulls.merge({
#               merge_method: "merge",
#               owner: context.repo.owner,
#               pull_number: context.payload.pull_request.number,
#               repo: context.repo.repo
#             });
