name: Merge PR from dev-bump-version-patch to dev

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - dev

jobs:
  merge_dev_bump_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Approve pull request"
        uses: "actions/github-script@v7"
        with:
          script: |
            const repository = context.repo;
            const reviewers = ['review-bot-1', 'review-bot-2'];

            for (const reviewer of reviewers) {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                event: 'APPROVE',
                body: `Approved by ${reviewer}`,
                reviewer: reviewer
              });
            }

      - name: Merge pull request
        if: github.event.pull_request.head.ref == 'dev-bump-version-patch'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.merge({
              merge_method: "merge",
              owner: context.repo.owner,
              pull_number: context.payload.pull_request.number,
              repo: context.repo.repo
            });
