name: Merge PR from dev-bump-version-patch to dev

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - dev

jobs:
  merge_dev_bump_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Approve pull request"
        uses: "actions/github-script@v6"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const repository = context.repo;
            const owner =  repository.owner;
            const reviewer1 = 'review-bot-1';
            const reviewer2 = 'review-bot-2';
            const pullRequestNumber = context.issue.number;
            
            // Przypisanie pull requesta do osoby pierwszej
            await github.issues.addAssignees({
              owner: owner,
              repo: context.repo.repo,
              issue_number: pullRequestNumber,
              assignees: [owner, reviewer1, reviewer2]
            });

            // Zatwierdzenie pull requesta przez obie osoby
            await github.pulls.createReview({
              owner: owner,
              repo: context.repo.repo,
              pull_number: pullRequestNumber,
              event: 'APPROVE',
              body: 'Approved by reviewer 1',
              reviewer: reviewer1
            });
            await github.pulls.createReview({
              owner: owner,
              repo: context.repo.repo,
              pull_number: pullRequestNumber,
              event: 'APPROVE',
              body: 'Approved by reviewer 2',
              reviewer: reviewer2
            });

      - name: Merge pull request
        if: github.event.pull_request.head.ref == 'dev-bump-version-patch'
        uses: actions/github-script@v5
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repository = context.repo;

            await github.rest.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: pullRequest.number,
              repo: repository.repo,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}